name: Deploy to FTP on push

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        composer install
        npm install

    - name: Build and test
      run: |
        phpunit
        npm run test

    - name: Deploy to FTP
      uses: actions/checkout@v2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: .
        server-dir: /path/to/destination/directory
